# Generated by Django 5.1.3 on 2025-02-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Health Center', 'Health Center')], max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('6 Weeks', '6 Weeks'), ('10 Weeks', '10 Weeks'), ('14 Weeks', '14 Weeks'), ('9-12 Months', '9-12 Months'), ('16-24 Months', '16-24 Months'), ('5-6 Years', '5-6 Years'), ('10 Years', '10 Years'), ('16 Years', '16 Years')], default='None', max_length=50)),
                ('vaccine_name', models.CharField(choices=[('None', 'None'), ('Oral Polio Vaccine (OPV) - 1', 'Oral Polio Vaccine (OPV) - 1'), ('Pentavalent - 1', 'Pentavalent - 1'), ('Rotavirus Vaccine (RVV) - 1', 'Rotavirus Vaccine (RVV) - 1'), ('Pneumococcal Conjugate Vaccine (PCV) - 1', 'Pneumococcal Conjugate Vaccine (PCV) - 1'), ('Inactivated Polio Vaccine (fIPV) - 1', 'Inactivated Polio Vaccine (fIPV) - 1'), ('Pentavalent - 2', 'Pentavalent - 2'), ('Measles & Rubella (MR) - 1', 'Measles & Rubella (MR) - 1'), ('Diphtheria Pertussis & Tetanus (DPT) - Booster 1', 'Diphtheria Pertussis & Tetanus (DPT) - Booster 1')], default='None', max_length=100)),
                ('administration', models.CharField(choices=[('Injection', 'Injection'), ('Oral', 'Oral')], default='Injection', max_length=50)),
                ('protection', models.CharField(choices=[('None', 'None'), ('Poliovirus', 'Poliovirus'), ('Diphtheria, Pertussis, Tetanus, Hepatitis B, Hib', 'Diphtheria, Pertussis, Tetanus, Hepatitis B, Hib'), ('Rotavirus (diarrhea)', 'Rotavirus (diarrhea)'), ('Pneumonia, meningitis, septicemia', 'Pneumonia, meningitis, septicemia'), ('Measles, Rubella', 'Measles, Rubella'), ('Japanese Encephalitis', 'Japanese Encephalitis'), ('Tetanus, Diphtheria', 'Tetanus, Diphtheria')], default='None', max_length=100)),
                ('side_effects', models.CharField(choices=[('None', 'None'), ('Swelling, redness, pain, fever', 'Swelling, redness, pain, fever'), ('Mild diarrhea, vomiting, irritation', 'Mild diarrhea, vomiting, irritation'), ('Soreness, fever', 'Soreness, fever'), ('Redness, swelling, loss of appetite, fever', 'Redness, swelling, loss of appetite, fever'), ('Pain, swelling, fever, headache, nausea', 'Pain, swelling, fever, headache, nausea')], default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProviderStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=50)),
                ('age_group', models.CharField(choices=[('6 Weeks', '6 Weeks'), ('10 Weeks', '10 Weeks'), ('14 Weeks', '14 Weeks'), ('9-12 Months', '9-12 Months'), ('16-24 Months', '16-24 Months'), ('5-6 Years', '5-6 Years'), ('10 Years', '10 Years'), ('16 Years', '16 Years')], max_length=50)),
                ('health_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.healthprovider')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='healthprovider',
            name='vaccines',
            field=models.ManyToManyField(blank=True, to='admin_app.vaccine'),
        ),
    ]
