# Generated by Django 5.1.3 on 2025-02-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_healthprovider_email_healthprovider_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprovider',
            name='vaccines',
            field=models.ManyToManyField(related_name='health_providers', to='admin_app.vaccine'),
        ),
    ]
