# Generated by Django 5.1.3 on 2025-03-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='max_children',
        ),
    ]
