# Generated by Django 5.1.3 on 2025-03-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='max_children',
            field=models.IntegerField(default=10),
        ),
    ]
