# Generated by Django 5.1.3 on 2025-03-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_booking_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='booking',
            name='age_group',
            field=models.CharField(choices=[('6 Weeks', '6 Weeks'), ('10 Weeks', '10 Weeks'), ('14 Weeks', '14 Weeks'), ('9-12 Months', '9-12 Months'), ('16-24 Months', '16-24 Months'), ('5-6 Years', '5-6 Years'), ('10 Years', '10 Years'), ('16 Years', '16 Years')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
