# Generated by Django 5.1.3 on 2025-03-01 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_booking_vaccine_booking_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.tbl_parent'),
        ),
    ]
