# Generated by Django 5.1 on 2025-03-04 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_booking_vaccines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user_app.tbl_parent'),
        ),
        migrations.AlterField(
            model_name='tbl_parent',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
