# Generated by Django 5.1.3 on 2025-02-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.healthprovider')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.vaccine')),
            ],
        ),
    ]
