# Generated by Django 5.1 on 2025-03-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_timeslot_available_spots'),
        ('health_provider_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrequest',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='vaccines',
            field=models.ManyToManyField(to='admin_app.vaccine'),
        ),
    ]
